#!/bin/bash

set -e

source setjdk_osx

while read jvm
do
    echo "Testing with $jvm"
    setjdk $jvm
    ../../gradlew clean test --rerun-tasks --info
done < supported_jvms

export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk11.0.7-zulu.jdk/Contents/Home/
../../gradlew clean test --info --rerun-tasks
